services:
# thêm service odoo
  db:
    image: postgres:13
    container_name: odoo-db
    # config env
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    # mapports
    ports:
      - "5432:5432"

  # odoo:
  #   image: odoo:14
  #   container_name: odoo-test
  #   ports:
  #     - "9000:8069"
  #   volumes:
  #   #  mount odoo.conf vao container
  #     - ./odoo.conf:/etc/odoo/odoo.conf
  #     - ./Odoo-Training/exam_addons:/mnt/extra-addons  # Mount thư mục exam_addons từ máy host vào container
  #   depends_on:
  #     - db_test

  # db_test:
  #   image: postgres:13
  #   container_name: odoo-db-test
  #   # config env
  #   environment:
  #     - POSTGRES_DB=odoo
  #     - POSTGRES_USER=odoo
  #     - POSTGRES_PASSWORD=odoo